### ISSUE TITLE
hook fails if comment tags not found

### ISSUE THREAD

**Issue by brandonjbjelland** [antonbabenko/pre-commit-terraform#17]
I would expect a tool like this to operate in a very standard mode, not trying to do anything like inserting between comments. This is your design decision to make but I'd much prefer a more standard execution of the tool like:

```
terraform-docs md ./ | cat -s | ghead -n -1 > README.md
```

This approach is markdown linter compliant and supports the standard of putting your documentation in the `main.tf`

<img width="817" alt="screen shot 2018-05-17 at 12 48 57 am" src="https://user-images.githubusercontent.com/2502520/40274676-a09cb89c-5b91-11e8-84e7-4aa47dbc05c0.png">

**Comment by antonbabenko** [comment]
My reasoning for making it using comments was that not everybody wants to overwrite the whole README.md but rather put it into specified section of that file.

Later we may have a possibility to specify which file to update instead of README.md as now.

Regarding the issue with `sed... unexpected EOF`. It is happening not because a comment tag was not found, but because `sed` command does not work on all platforms equally well (I tested it with brew'ed sed on Mac). The most platform agnostic way seems to be using Perl (#15).

I will keep this issue posted when a new pre-commit hook is released (during today or tomorrow).

**Comment by antonbabenko** [comment]
[v1.7.2](https://github.com/antonbabenko/pre-commit-terraform/releases/tag/v1.7.2) is using Perl and keeps a temporary file in a temporary directory.

Please give it a try and let us know how it goes.

**Comment by BennyHarv3** [comment]
v1.7.3 at least got me past this error. I wanted all of the documentation in `main.tf` to overwrite the README.md. The hook doesn't actually write the README contents like #7 asks for still, but this could probably be closed.
