### ISSUE TITLE
add compatibility with Terraform v0.12.x

### ISSUE THREAD

**Issue by timobartels** [antonbabenko/pre-commit-terraform#40]
Due to syntax changes with new Terraform version 0.12.x, this webhook will fail on terraform code that follows the new TF 0.12 syntax.

**Comment by snemetz** [comment]
There are multiple hooks. Which ones are you referring to?

**Comment by antonbabenko** [comment]
Make sure you have the correct version of `terraform` binary to be able to work with 0.12 files. These hooks are just using available binary and don't have extra logic based on a version of Terraform.

Though `terraform_docs` should be disabled when using Terraform 0.12 because it is not compatible yet.

**Comment by antonbabenko** [comment]
[v1.12.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.12.0) has been released with the updated note about `terraform-docs`.
