### ISSUE TITLE
add pluralith pre-commit hook

### ISSUE THREAD

**Issue by tbugfinder** [antonbabenko/pre-commit-terraform#412]
### What problem are you facing?

Although IaC is nice, we also love diagrams of what's getting deployed.
Based on diagrams as code there are also approaches to build those based on terraform code having current diagrams of the code base.
https://www.pluralith.com/ supports this approach.

### How could pre-commit-terraform help solve your problem?

A pluralith pre-commit hook would be beneficial to support the development lifecycle.

**Comment by yermulnik** [comment]
@tbugfinder I took a look at https://www.pluralith.com/ and https://github.com/Pluralith/pluralith-cli and it looks like Pluralith doesn't fall under what `pre-commit` is used for:
> Git hook scripts are useful for identifying simple issues before submission to code review. We run our hooks on every commit to automatically point out issues in code such as missing semicolons, trailing whitespace, and debug statements. By pointing these issues out before code review, this allows a code reviewer to focus on the architecture of a change while not wasting time with trivial style nitpicks.

Let me know if I'm mistaken though.
Otherwise if you feel inspired, please feel free to contribute (https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/CONTRIBUTING.md) and we'll consider including your hook as an optional (and respectively off by default) hook for those who'd like to re-build Pluralith graphs on every GIT commit. However I think it's still much better to run Pluralith on PR creation as a webhook (or else).
Thank you.

**Comment by MaxymVlasov** [comment]
Let it goes from Alpha to Beta first

```bash
➜ pluralith plan
initializing application directories failed -> initApp: InitPaths: mkdir /usr/bin/Pluralith: permission denied
⠿ Running Plan ⇢ Apply in the Pluralith UI

✘ Failed to launch Pluralith
launching Pluralith failed -> RunTerraform: could not run launch command -> LaunchPluralith: runOsCommand: fork/exec /usr/bin/AppData/Local/Programs/pluralith/Pluralith.exe: no such file or directory
```
