### ISSUE TITLE
pre-commit run --all-files with many files does not work as intended with language script

### ISSUE THREAD

**Issue by anrub** [antonbabenko/pre-commit-terraform#443]
### Describe the bug

The function [is_hook_run_on_whole_repo](https://github.com/antonbabenko/pre-commit-terraform/blob/master/hooks/_common.sh#L145) checks if the hook is executed on all files by verifying the passed in files (supplied from pre-commit itself) with the maximal checkable files, by running [git ls-files](https://github.com/antonbabenko/pre-commit-terraform/blob/master/hooks/_common.sh#L161), this is never true, if the files get partitioned by [xargs from pre-commit](https://github.com/pre-commit/pre-commit/blob/0239b27f4ffb37d56b94ac3f9aecef22300daf19/pre_commit/languages/helpers.py#L132), which happens if there are a lot of files in the repository.

### How can we reproduce it?

Run "terragrunt fmt" in a large repo and compare time to "pre-commit run -a"

e.g. test repository: https://github.com/anrub/terragrunt-fmt-pre-commit-errors 

```bash
$ time terragrunt hclfmt

real	0m0,936s
user	0m0,582s
sys	0m0,598s
```

```bash
$ time pre-commit run -a

real	0m7,992s
user	0m31,527s
sys	0m12,224s
```

### Environment information

* OS:  Ubuntu 22.04.1

* `uname -a` output:

```
Linux xx-xubuntu 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

* Tools availability and versions:

[see test repository.
](https://github.com/anrub/terragrunt-fmt-pre-commit-errors/blob/main/.tool-versions)

* `.pre-commit-config.yaml`:

[see test repository](https://github.com/anrub/terragrunt-fmt-pre-commit-errors/blob/main/.pre-commit-config.yaml).

**Comment by yermulnik** [comment]
Interesting use case. It seems like this hasn't came up yet for anyone else here 🤷🏻
I took a quick look into `pre-commit` code and it looks like it's how it works for large repos (passing portions of files like `xargs` would do to adhere to cmdline length limits — actually this is what you outlined above), which is what your timing tests show: running single `terragrunt hclfmt` command vs running `terragrunt_fmt` hook multiple times based on number of "portions" of files passed in from `pre-commit`.
So our implementation of `common::is_hook_run_on_whole_repo` function was seemingly based on a way smaller repo than yours and the implementation was more of a quirk since `pre-commit` doesn't provide any option to determine whether it was ran with `--all-files` parameter or not.
Since I couldn't find any clue on how to figure out the presence of `--all-files` parameter passed to `pre-commit run`, it may worth to file a request in `pre-commit` repo and ask to add e.g. a variable visible in scope of hooks environment. Just like they do for some other parameters passed via arguments (https://github.com/pre-commit/pre-commit/blob/main/pre_commit/commands/run.py#L392-L399).
If there are any other clues on how to figure out whether `pre-commit run` had `-a` (`--all-files`) passed via args, that would be appreciated.

**Comment by yermulnik** [comment]
I do believe there should have been alike requests in `pre-commit` repo as it's not only us who has hooks which might be ran over _entire repo_ rather than over _all files in repo_. Though I couldn't make up a search query in `pre-commit` issues which would give me something relevant =(

**Comment by anrub** [comment]
thanks for following up. I am stepping through and it must be something with the file/list-handling, maybe even in pre-commit itself. I removed the terragrunt execution complete form the code and it takes 5 seconds just to run, without any terragrunt at all in the code.

**Comment by yermulnik** [comment]
Interesting observation. Thanks for update @anrub 
Looking at https://github.com/pre-commit/pre-commit/issues/2556 I seem to think we have no option from `pre-commit` end to figure its execution behavior.
Probably running `pre-commit` in debug mode (if it has an option to track the calls made and show respective timestamps), we can see which "item" in the chain takes much time and understand whether it's us to re-design respective hook, or the issue is somewhere else.

What I mean is that running `terragrunt-fmt` hook is a chain of "hand overs" from git to pre-commit, next to pre-commit-terraform, next to shell-based hook, next to terragrunt fmt (maybe something else in between). And given `xargs` functionality of `pre-commit` (which is actually a very good stuff) this chain is multiplied several times on your repo. So it's obvious that there's a difference in timings as compared to simple `terragrunt fmt` run (whichever correct syntax is 😝) 🤷🏻 
Kinda don't use that large monorepo like this if you'd like to save several seconds of life =)

**Comment by anrub** [comment]
yes, surely I like a smaller repo :smile: 
Just found it interesting, that the execution times of the terragrunt fmt are so different in the action, but no very big problem of course.

Thank you very much, for your response and discussion! From my side we could close on this.

**Comment by yermulnik** [comment]
> Just found it interesting, that the execution times of the terragrunt fmt are so different in the action

It seems to be a consequence of the difference between running `terragrunt` directly on entire repo and running it via the framework and wrapper hook. We still need to investigate where the "slowness" gets introduced exactly. Though it's a scope of another repo issue.

**Comment by MaxymVlasov** [comment]
I just propose not running `terragrunt_fmt` hook by `pre-commit run --all` too often/in any time-dependent job.

By the way, that is a wide recommendation - do not use `--all` at all, better flow is:
1. Fix/disable all errors in codebase
2. Introduce pre-commit check as required CI step in each PR/MR
3. Once in half-year manually check the repo by `pre-commit --all` that no one introduces violations using administrative privileges.
