### ISSUE TITLE
Pre-commit hook showed me that it passed Terragrunt validate when it should not

### ISSUE THREAD

**Issue by natsumemaya** [antonbabenko/pre-commit-terraform#444]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/48797743/198247434-4df76668-40ba-4dbc-a331-a7d10bd0e2b6.png)

When validate was ran separately it works:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/48797743/198248188-99fbe4de-3fb0-4179-9070-3e58a5b7609c.png)

Pre-commit can identify Errors only in .hcl file:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/48797743/198248450-91f96ae9-621f-47e6-bff6-8883ee5bcfa2.png)

We got errors when we did any changes in main (top lvl) terragrunt.hcl
That why we had to use `exclude` to suppress it.

![Screenshot 2022-10-27 104729](https://user-images.githubusercontent.com/48797743/198252207-f0d3a92e-6d55-434f-92b3-bc5801f60b89.jpg)

 And also use `files: envs\/[a-z]*\/^terragrunt.hcl` didnt work . It showed fake "pass" alway.

**Comment by natsumemaya** [comment]
My regex is correct, given by you not. 

Sure i did changes it my .hcl files across all environments deliberately, to check if pre-commit would identify and make checks. 
So well it does, when changes only in the most deep "terragrunt.hcl" but any related code to this and others files just dont , as you can see on first screenshot. It passes check when it should not...

**Comment by MaxymVlasov** [comment]
>My regex is correct, given by you not.

```bash
➜ ipython
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import re

In [2]: re.search('envs\/[a-z]*\/^terragrunt.hcl', 'envs/sdgsdgsdgsdg/terragrunt.hcl')

In [3]: re.search('^envs/[a-z]+/terragrunt\.hcl$', 'envs/sdgsdgsdgsdg/terragrunt.hcl')
Out[3]: <re.Match object; span=(0, 32), match='envs/sdgsdgsdgsdg/terragrunt.hcl'>

In [4]:
```

**Comment by natsumemaya** [comment]
![image](https://user-images.githubusercontent.com/48797743/198583345-f18b6965-663d-4ed2-9cb1-636f1b333a48.png)

My regex works, it tested with pre-commit and it checks "terragrunt.hcl" files or i tested it when switched it to use "env.hcl" files and it works.

**Comment by MaxymVlasov** [comment]
![image](https://user-images.githubusercontent.com/11096782/198630292-a1bdaa95-880b-41eb-99d7-0655e9e8d662.png)

I little bit adjust regex to work with your examples, by adding slash to group
`^envs/[a-z/]+/terragrunt\.hcl$`

![image](https://user-images.githubusercontent.com/11096782/198630784-e5bb9c24-1f25-4197-895b-43aaa46c34e0.png)

**Comment by yermulnik** [comment]
> `^envs/[a-z/]+/terragrunt\.hcl$`

Technically it should better be `^envs/([a-z]+/)+terragrunt\.hcl$`

> Meanwhile when i run `terragrunt validate` command itself, without `pre-commit` it identifies all Errors. SO `pre commit` has problems not `terragrunt validate` itself

There's a difference between how Terragrunt standalone binary works and how `pre-commit` framework does its job.
In former case Terragrunt traverses hierarchy on its own thus making it possible for it to designate top-level hcl-file from env-specific hcl-files w/o any relation to whether its a GIT repo or plain directory.
In latter case `pre-commit` framework (not `pre-commit-terraform` as a subset of `pre-commit` farmework, but a "parent" framework) collects files changed in current commit, splits them into bunches if needed, and passes the list(s) of files to `pre-commit` hook, which is `terragrunt_validate` in this case, which in its turn "relays" this to underlying Terragrunt binary, thus final command looks something like `terragrunt validate path/to/file1 path/to/file2 ...`, which as you may see is different from the former case.

So what you might want to try is `always_run` hook config option (see https://pre-commit.com/#new-hooks for details) to **always** run `terragrunt_validate` no matter whether there are matching files in current commit. And if your repo has limited number of files so that `pe-commit` framework doesn't do filelist splitting, then you should be fine with your use case.
