### ISSUE TITLE
terraform_trivy not excluding paths

### ISSUE THREAD

**Issue by dennisroche** [antonbabenko/pre-commit-terraform#617]
### Describe the bug

```
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_trivy
        exclude: '/examples/'
```

This configuration is still scanning terraform included in `example` folders in external modules. As this isn't code that I'm deploying, I would like to exclude it from the check.

### How can we reproduce it?

**N.B** the path is `ecs_alb_service_task\**examples**\complete\main.tf`

<details><summary>Trivy avd-aws-0178</summary>

```bash
MEDIUM: VPC Flow Logs is not enabled for VPC
════════════════════════════════════════
VPC Flow Logs provide visibility into network traffic that traverses the VPC and can be used to detect anomalous traffic or insight during security workflows.

See https://avd.aquasec.com/misconfig/avd-aws-0178
────────────────────────────────────────
 cloudposse/vpc/aws/main.tf:30-49
   via .terraform\modules\ecs_alb_service_task\examples\complete\main.tf:9-16 (module.vpc)
────────────────────────────────────────
  30 ┌ resource "aws_vpc" "default" {
  31 │   count = local.enabled ? 1 : 0
  32 │
  33 │   #bridgecrew:skip=BC_AWS_LOGGING_9:VPC Flow Logs are meant to be enabled by terraform-aws-vpc-flow-logs-s3-bucket and/or terraform-aws-cloudwatch-flow-logs
  34 │   cidr_block          = local.ipv4_primary_cidr_block
  35 │   ipv4_ipam_pool_id   = try(var.ipv4_primary_cidr_block_association.ipv4_ipam_pool_id, null)
  36 │   ipv4_netmask_length = try(var.ipv4_primary_cidr_block_association.ipv4_netmask_length, null)
  37 │   # Additional IPv4 CIDRs are handled by aws_vpc_ipv4_cidr_block_association below
  38 └
  ..
────────────────────────────────────────
```

</details>

### Environment information

```bash
OS Name:                   Microsoft Windows 11 Pro Insider Preview
OS Version:                10.0.23612 N/A Build 23612
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

* Tools availability and versions:

```bash
trivy --version
Version: 0.48.3
Policy Bundle:
  Digest: sha256:f21e8e92a7b3f6042ef7acfd3b799afc1648536dc4111c4d5458bc16396f8332
  DownloadedAt: 2024-02-06 01:27:11.6126431 +0000 UTC
```

<details><summary>.pre-commit-config.yaml</summary>

```bash
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_trivy
        exclude: '/examples/'
```

</details>

**Comment by dennisroche** [comment]
also, this `.terraform` directory that the examples are in the `.gitignore` so they shouldn't be going through the pre-commit

**Comment by MaxymVlasov** [comment]
Please let us know when `trivy` adds the ability to disable [recursive scanning](https://aquasecurity.github.io/trivy/v0.41/docs/configuration/others/#skip-directories).

I suggest you open a feature request in [trivy repo](https://github.com/aquasecurity/trivy) and link this issue.

As a quick fix, use args as specified in [README point 3](https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_trivy), and provide to trivy itself [`--skip-dirs`](https://aquasecurity.github.io/trivy/v0.41/docs/configuration/others/#skip-directories).

**Comment by MaxymVlasov** [comment]
> also, this `.terraform` directory that the examples are in the `.gitignore` so they shouldn't be going through the pre-commit

And they are not. 

pre-commit sends only next modified files to `terraform_trivy` hook:
https://github.com/antonbabenko/pre-commit-terraform/blob/995a59d4c30c7710a640aba2bb430265677894c5/.pre-commit-hooks.yaml#L100-L101

We calculate which dirs are affected (because TF visibility is all files with specific extensions in the directory, not a single file) 
https://github.com/antonbabenko/pre-commit-terraform/blob/995a59d4c30c7710a640aba2bb430265677894c5/hooks/_common.sh#L212-L215C5

and send a list of affected dirs to `trivy` binary
https://github.com/antonbabenko/pre-commit-terraform/blob/995a59d4c30c7710a640aba2bb430265677894c5/hooks/_common.sh#L253

https://github.com/antonbabenko/pre-commit-terraform/blob/995a59d4c30c7710a640aba2bb430265677894c5/hooks/terraform_trivy.sh#L45

Why `trivy` scans `.terraform` and ignore `,gitignore` - that's a good question for `trivy` maintainers. I think they have already plenty of these questions like this one - https://github.com/aquasecurity/trivy/issues/3670

**Comment by dennisroche** [comment]
@MaxymVlasov thanks for the detailed reply; I will take this up with the `trivy` project.
